# Generated by Django 5.2.3 on 2025-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('year_of_exp', models.IntegerField()),
                ('join_date', models.DateField()),
            ],
        ),
    ]
